source 'https://github.com/CocoaPods/Specs.git'

target 'DRDNetworking_Example', :exclusive => true do
  pod 'DRDNetworking', :path => '../'
end

target 'DRDNetworking_Tests', :exclusive => true do
  pod 'DRDNetworking', :path => '../'

  pod 'Specta'
  pod 'Expecta'
  pod 'OCMock'
end
